public enum TaskType {

    NEW, TAKEOFF, LANDING, DEFAULT, REQUEST_TRAJECTORY, RESPONSE_NEWFLIGHT, RESPONSE_TAKEOFF, RESPONSE_LANDING, REQUEST_NEWFLIGHT, REQUEST_TAKEOFF, REQUEST_LANDING
,   REQUEST_CHANGE_COURSE}
